# Generated by Django 2.0.6 on 2018-06-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgeneral',
            name='photo_path',
        ),
        migrations.AlterField(
            model_name='photo',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photopaths', to='event.EventGeneral'),
        ),
    ]
