# Generated by Django 2.0.6 on 2018-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180626_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgeneral',
            name='number_like',
            field=models.IntegerField(auto_created=0),
        ),
    ]
